
; ------------------------------------------------------------
; TABLEAU DE VECTEURS TITRE
; ------------------------------------------------------------
ARRAY_IM1_TITRE:
    DEFW F_IM1_SKIP                 ; Index 0 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 1 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 2 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 3 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 4 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 5 → pointe vers INT_SKIP
