
FIRMWARE

.GRA_SET_PEN        equ #BBDE
.GRA_TEST_ABSOLUTE  equ #BBF0
.GRA_PLOT_ABSOLUTE  equ #BBEA 

.SCR_SET_MODE       equ #BC0E
.SCR_SET_INK        equ #BC32
.SCR_SET_BORDER     equ #bc38
.SCR_SET_FLASHING   equ #bc3e

.SCR_GET_MODE       equ #BC11
.SCR_GET_INK        equ #BC35
.SCR_GET_BORDER     equ #BC3B
.SCR_GET_FLASHING   equ #BC41
.SCR_GET_LOCATION   equ #BC0B

.TXT_WR_CHAR        equ #bb5d
.TXT_SET_CURSOR     equ #bb75

.kl_l_rom_enable 	equ #b906
.kl_l_rom_disable 	equ #b909
.kl_u_rom_disable 	equ #b903

