
; ------------------------------------------------------------
; TABLEAU DE VECTEURS DE LA SCENE GAME
; ------------------------------------------------------------

ARRAY_IM1_JEU
    DEFW F_IM1_SKIP                 ; Index 0 → pointe vers INT_SKIP
    DEFW F_IM1_SCAN_KEYBOARD        ; Index 1 → Lecture matrice du clavier
    DEFW F_IM1_SKIP                 ; Index 2 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 3 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 4 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 5 → pointe vers INT_SKIP
