; ------------------------------------------------------------
; TABLEAU DE VECTEURS MENU
; ------------------------------------------------------------
ARRAY_IM1_MENU:
    DEFW F_IM1_COMPTEUR_FRAME       ; Index 0 → pointe vers COMPTEUR FRAME
    DEFW F_IM1_SCAN_KEYBOARD        ; Index 1 → pointe vers SCAN CLAVIER
    DEFW F_IM1_SKIP                 ; Index 2 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 3 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 4 → pointe vers INT_SKIP
    DEFW F_IM1_SKIP                 ; Index 5 → pointe vers INT_SKIP
