
; =============================================================================
; FONCTION    : F_ATTENTE_VBL
; =============================================================================
; Description : Bloque le CPU en attente du signal de synchronisation verticale 
;               (VBL / VSYNC) de l'écran. Aligne le jeu sur un timing de 50 Hz.
; Entrée      : Aucune
; Sortie      : Aucune
; Modifie     : AF
; =============================================================================
